### ISSUE TITLE
Why OpenSOC need TWO network capture cards?

### ISSUE THREAD

**Issue by ghost** [OpenSOC/opensoc#1]
I noticed a requirement in the topic "What do I need to run OpenSOC" of "http://opensoc.github.io/": 2 Network Capture Cards. So, why we need two network capture cards? One is not enough?

**Comment by cembree** [comment]
Hi Yubin,

In the standard OpenSOC configuration, we have 1 capture card for raw
PCAP data.
We have a 2nd capture card for Deep Packet Inspection.  We use BRO in
our normal configuration.

We have found that with any significant network traffic, the workload
for PCAP and DPI is more than can be handled on a single card.

Hope that helps,
Chris

**Comment by wybwzl** [comment]
Thank you:)

When I saw the "standard OpenSOC configuration", I just thought of a report named "Cisco OpenSOC Hadoop Design with Bro". In this report, grutz said that OpenSOC is not easy to install and get working quickly. But I have not found the details about how install it on the github. So, is there any document or guide could tell us how to install it with "standard OpenSOC configuration" and let it work?
