### ISSUE TITLE
How to setup an OpenSOC running environment from zero? 

### ISSUE THREAD

**Issue by kingcca** [OpenSOC/opensoc#2]
I want to set up an OpenSOC running environment for more learning and verify,  but i haven't found any suggestion for that.  it said the OpenSOC wiki page can give the installation guide. But i can find it. Who has done it before, i an very appreciate if someone can share the experience for that.

**Comment by Oneiroi** [comment]
Indeed there's a fair amount of detail missing; prior experience of Hadoop et al is assumed

And documentation is just plain missing, take this from the readme of opensoc-streaming:

```
For OpenSOC FAQ please read the following wiki entry: https://github.com/OpenSOC/opensoc-streaming/wiki/OpenSOC-FAQ
```

The link is to create a new page ...

Even some high level document on connecting the packet streams to the opensoc-stream component would be greatly appreciated.

**Comment by grutz** [comment]
OpenSOC has evolved to Apache Metron: https://metron.apache.org/
