### ISSUE TITLE
Where is OpenSOC-ML module?

### ISSUE THREAD

**Issue by jerrychenhf** [OpenSOC/opensoc#4]
Hi,
I didn't see OpenSOC-ML module anywhere. And the project is inactive for a long time missing the most important part.

**Comment by ddutta** [comment]
OpenSOC has moved to the Apache incubator under the name "Metron"
https://metron.incubator.apache.org

On Sun, Feb 14, 2016 at 12:36 AM, Chen Haifeng notifications@github.com
wrote:

> Hi,
> I didn't see OpenSOC-ML module anywhere. And the project is inactive for a
> long time missing the most important part. Is OpenSOC only a Cisco PR?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/OpenSOC/opensoc/issues/4.

## 

-Debo~
