### ISSUE TITLE
Status of the Project

### ISSUE THREAD

**Issue by jiangytcn** [OpenSOC/opensoc#5]
Hi Community

Is there anyone can update the status of this project ? we would like to evaluate this project and adopt it in our solution,  what's the story behind of the current situation ? 

appreciate your help

**Comment by ChrisEmbreee** [comment]
OpenSOC has effectively been migrated to Apache project Metron. https://metron.apache.org/

**Comment by grutz** [comment]
Yes indeed. OpenSOC was a great foundation and Metron is a fantastic evolution.
